### ISSUE TITLE
adding the example config breaks the config

### ISSUE THREAD

**Issue by bobloadmire** [LordBoos/discord_game#14] opened 2020-07-24 04:47 UTC
I added the example config, replacing with my token and usernames, and when I hit check configuration, it just spins circles. As soon as I remove the discord_game entry its valid again.

**Comment by LordBoos** [comment] 2020-07-24 07:14
Tell me the steps you did to be in this state. Have you installed this component from HACS and then added the example config without first restarting HA? Thing is that HA thinks it is invalid config, because component is not loaded until you first restart HA.

**Comment by bobloadmire** [comment] 2020-07-25 17:21
HA has been restarted. Heres my config:

sensor:
  - platform: discord_game
    token: <redacted>
    image_format: webp
    members:
      - deinekabel#xxxx
      - spandy24#xxxx
      - Raithmaster1#xxxx
      - Michael.Zumwalt#xxxx
      - Zummie#xxxx


Up saving the yaml, and clicking check config, it just has the loading circle indefinately until I reload the page.

**Comment by C0NTi** [comment] 2020-07-25 21:38
> HA has been restarted. Heres my config:
> 
> ```
> sensor:
>   - platform: discord_game
>     token: <redacted>
>     image_format: webp
>     members:
>       - deinekabel#xxxx
>       - spandy24#xxxx
>       - Raithmaster1#xxxx
>       - Michael.Zumwalt#xxxx
>       - Zummie#xxxx
> ```
> 
> Up saving the yaml, and clicking check config, it just has the loading circle indefinately until I reload the page.
> 
> I also uninstalled/reinstalleed from HACS and did multiple reboots

Have you tried it without Michael?

**Comment by LordBoos** [comment] 2020-07-25 21:55
Yea that might cause it. Try to quote him.
`- 'Michael.Zumwalt#xxxx'`

**Comment by bobloadmire** [comment] 2020-07-25 23:50
honest to god, it just started working and I have no clue why. I didn't have to quote the user with the period either

**Comment by LordBoos** [comment] 2020-07-26 15:52
I was not able to reproduce the issue. Closing this for now.

**Closed by LordBoos** 2020-07-26 15:52 UTC
